services:
    postgres:
        image: postgres:13

        environment:
            POSTGRES_PASSWORD: password

        volumes:
            - 'postgres-data:/var/lib/postgresql/data'
            - ./init-dev-db.sql:/docker-entrypoint-initdb.d/init.sql
    vscode:
        build:
            context: .
            dockerfile: Dockerfile

        environment:
            # Required for the `diesel` CLI to work.
            DATABASE_URL: postgres://postgres:password@postgres/postgres

        volumes:
            # Mounts the project folder to '/workspace'. While this file is in .devcontainer,
            # mounts are relative to the first file in the list, which is a level up.
            - ..:/workspace:cached

        # [Optional] Required for ptrace-based debuggers like C++, Go, and Rust
        cap_add:
            - SYS_PTRACE
        security_opt:
            - seccomp:unconfined

        # Overrides default command so things don't shut down after the process ends.
        command: /bin/sh -c "while sleep 1000; do :; done"

volumes:
    postgres-data:
